---
# MultiAgentSimulations
# Classes and kwargs

simulations: !!omap
  - outdoor:
      module: "crowddynamics.examples"
      class: "Outdoor"
      kwargs: !!omap
        - size: 100
        - model: "three_circle"
        - body: "adult"
        - height: 20.0
        - width: 20.0

  - hallway:
      module: "crowddynamics.examples"
      class: "Hallway"
      kwargs: !!omap
        - size: 100
        - model: "three_circle"
        - body: "adult"
        - height: 5.0
        - width: 20.0

  - rounding:
      module: "crowddynamics.examples"
      class: "Rounding"
      kwargs: !!omap
        - size: 100
        - model: "circular"
        - body: "adult"
        - height: 15.0
        - width: 15.0

  - room_evacuation:
      module: "crowddynamics.examples"
      class: "RoomEvacuation"
      kwargs: !!omap
        - size: 200
        - model: "circular"
        - body: "adult"
        - height: 20.0
        - width: 10.0
        - door_width: 1.2
        - exit_hall_width: 2.0
        - spawn_shape: "circ"

  - room_evacuation_massive:
      module: "crowddynamics.examples"
      class: "RoomEvacuation"
      kwargs: !!omap
        - size: 1000
        - model: "circular"
        - body: "adult"
        - height: 40.0
        - width: 20.0
        - door_width: 1.2
        - exit_hall_width: 2.0
        - spawn_shape: "circ"

  - room_evacuation_game:
      module: "crowddynamics.examples"
      class: "RoomEvacuationGame"
      kwargs: !!omap
        - size: 300
        - model: "circular"
        - body: "adult"
        - height: 20.0
        - width: 10.0
        - door_width: 1.2
        - exit_hall_width: 2.0
        - spawn_shape: "circ"
        - t_aset_0: 200.0
        - interval: 0.1
        - neighbor_radius: 0.4
        - neighborhood_size: 8


# Qt mappings for the kwargs
# int    -> QSpinBox        [min, max]
# float -> QDoubleSpinBox  [min, max]
# string -> QComboBox       [string,...]
# bool   -> QRadioButton    {true, false}
kwarg_mapping:
  size: [1, null]
  model: ["circular", "three_circle"]
  body: ["adult", "male", "female", "child", "eldery"]
  height: [0, null]
  width: [0, null]
  door_width: [0, 3]
  exit_hall_width: [0, null]
  spawn_shape: ["circ", null]
  t_aset_0: [0, null]
  interval: [0, 1]
  neighbor_radius: [0, null]
  neighborhood_size: [1, null]

...