# Install env with command:
# conda env create -f environment.yml

name: crowd36
channels:
    - conda-forge
dependencies:
    - python=3.6
    - numpy
    - numba
    - scipy
    - scikit-image
    - shapely
    - matplotlib
    - bokeh
    - pip:
        - configobj
        - loggingtools
        - git+https://github.com/jaantollander/cell_lists.git
        - typing
        - sortedcontainers
        - anytree
        - ruamel.yaml
        - scikit-fmm
        - click
        - colorama
        - colorlog
        - traitlets
        - traittypes
        - diskcache
